# Generated by Django 5.0.1 on 2024-02-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(default=True, upload_to='')),
                ('image', models.ImageField(default=True, upload_to='')),
            ],
            options={
                'db_table': 'emp',
            },
        ),
    ]
